### ISSUE TITLE
Since about a month, the hook takes a very long time to complete

### ISSUE THREAD

**Issue by Strykar** [tylerjl/overdue#4]
Since about a month ago, overdue takes over 5-10 mins to complete, it would not take this long before, but it is working as intended. I will try to get a timed run the next time there are relevant updates, since now the results seem cached.
```
$ sudo sh -c "time /usr/bin/overdue"
The following daemons/units have stale file handles open to
libraries that have been upgraded. Consider restarting them
if they should reference updated shared libraries.
● init.scope
● rtkit-daemon.service
● systemd-journald.service
● systemd-logind.service
● systemd-machined.service
● systemd-timesyncd.service
● systemd-udevd.service
● user@1000.service

real	0m0.985s
user	0m0.269s
sys	0m0.429s
```

**Comment by tylerjl** [comment]
@Strykar thank you for reporting this!

The only command that I would imagine is resource intensive would be `lsof` since it's interrogating all the open system file handles. Even if the results of `lsof` get cached somewhere, it would be interesting to see what the total count of deleted file handles is to get a sense for whether that's an exceptionally large number and causing a slowdown.

Something like `lsof -d DEL 2>/dev/null | wc -l` would tell us whether the system has a huge number of these.

**Comment by Strykar** [comment]
Shows 782 right now..
EDIT: Ran this a few times today and it doesn't appear to go over 1000.

Updated the hook to:
`/usr/bin/bash -c '/usr/bin/lsof -d DEL 2>/dev/null | /usr/bin/wc -l' && /usr/bin/bash -c '/usr/bin/time /usr/bin/overdue'`
..will report back.

**Comment by Strykar** [comment]
1267 today with overdue taking 15 mins to complete, so doesn't seem like a file handle numbers issue?

**Comment by tylerjl** [comment]
Hmm. overdue is a _really_ simple program; the [hook script](https://github.com/tylerjl/overdue/blob/f5799d45f68212d588e5bcb75ec6e5fa7fd0c8f9/src/overdue.sh) really only invokes `lsof`, `awk`, and `ps`. The [hook](https://github.com/tylerjl/overdue/blob/f5799d45f68212d588e5bcb75ec6e5fa7fd0c8f9/src/overdue-libraries-upgrade.hook) watches for changes to `/lib` directories.

Because the script is so simple, you might be able to pin down where the delay is by adding some lines like `echo Begin ; date` and `echo Right before lsof ; date` and `echo After lsof ; date`. If `lsof` is what's slow, the delay should be plain there.

If that's slow, maybe we can find some `lsof` flags that focus on deleted handles more narrowly to avoid hitting many parts of the filesystem. Otherwise, if that isn't slow, we can look elsewhere.

**Comment by Strykar** [comment]
Closing, as I cannot repro the issue right now.
